name: apple_music_search
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"




dependencies:
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  just_audio: ^0.9.24
  dartz: ^0.10.1
  flutter_bloc: ^8.0.0
  json_serializable: ^6.2.0
  data_connection_checker: ^0.3.4
  json_annotation: ^4.5.0
  equatable: ^2.0.3
  injectable: ^1.5.0
  google_fonts: ^2.1.1
  alice: ^0.2.5
  freezed_annotation: ^2.0.3
  connectivity_plus: ^2.2.0
  dio: ^4.0.6
  bloc: ^8.0.3
  dio_logging_interceptor: ^1.0.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  build_runner: ^2.0.6
  connectivity: ^3.0.6
  flutter_launcher_icons: ^0.9.0
  freezed: ^2.0.3+1
  injectable_generator: ^1.4.1
  lint: ^1.7.2
  logger: ^1.1.0

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
